version: '3.8'

services:
  db:
    image: mariadb:10.4
    container_name: db
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  phpmyadmin:
    build:
      context: .
      dockerfile: phpmyadmin.Dockerfile
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/local
      - ./apache-config-phpmyadmin.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  
volumes:
  mariadb-data: